export const theme = {
  screenBg: "#F9FBFC",
  blurColor: "#777",
  focusColor: "#111",
  buttonBgPrimary: "#222",
  buttonTextPrimary: "#efefef",
  buttonBgSecondary: "#efefef",
  buttonTextSecondary: "#111",
  buttonBgTertiary: "red",
  buttonTextTertiary: "white",
  buttonBorderRadius: 5,
  buttonPadding: 10,
  inputButtonMarginVertical: 5,
  textLinkColor: "#0982ec",
};
