const colors = {
  INTERNATIONAL_ORANGE_GOLDEN_GATE_BRIDGE: "#C03221",
  GHOST_WHITE: "#F7F7FF",
  DEEP_CHAMPAGNE: "#F2D0A4",
  INDEPENDENCE: "#545E75",
  VIRIDIAN: "#3F826D",
  DODGER_BLUE: "#1e90ff",
};
export const theme = {
  screenBg: "#F9FBFC",
  blurColor: "#777",
  focusColor: "#111",
  buttonBgPrimary: colors.DODGER_BLUE,
  buttonTextPrimary: "#efefef",
  buttonBgSecondary: "#dedede",
  buttonTextSecondary: "#010101",
  buttonBgTertiary: "#222",
  buttonTextTertiary: "#efefef",
  buttonBorderRadius: 5,
  buttonPadding: 10,
  inputButtonMarginVertical: 5,
  textLinkColor: "#0982ec",
  barBgPrimary: colors.VIRIDIAN,
  barTextPrimary: "#ddd",
  barBgSecondary: colors.INDEPENDENCE,
  barTextSecondary: "#ddd",
  barBgTertiary: colors.DEEP_CHAMPAGNE,
  barTextTertiary: "#010101",
  placeholderColor: "#bbb",
  pickerBgBlur: "#dedede",
  pickerBgFocus: "#eee",
  pickerBorderColorFocus: "#aeaeae",
};
